spring:
  application:
    name: slow-service-client

server:
  port: 8080

logging:
  level:
    org.springframework: info
    io.github.resilience4j: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus